### ISSUE TITLE
"sonmcli token balance" periodically dumps an error

### ISSUE THREAD

**Issue by DPolygalov** [sonm-io/core#1356] opened 2018-08-28 16:23 UTC
[ERR] cannot load balance: rpc error: code = Unknown desc = cannot get live token balance: failed to get Ethereum balance: json: cannot unmarshal hex string without 0x prefix into Go value of type *hexutil.Big

**Comment by sshaman1101** [comment] 2018-08-28 18:05
I cannot reproduce this issue on the current master branch on both test and live nets. I'd close it for now.

**Closed by sshaman1101** 2018-08-28 18:05 UTC
Labels: S: Node, T: bug
