### ISSUE TITLE
Tag in task.yaml is not processed

### ISSUE THREAD

**Issue by DPolygalov** [sonm-io/core#1491] opened 2018-09-14 17:27 UTC
DEV-908
Judging by the example task.yaml, there is an option to set the tag.
But it either is not processed, or it does not appear in the task list and task status.

**Comment by sshaman1101** [comment] 2018-09-17 13:33
Tested with the latest master cannot reproduce. Probably this issue was fixed in #1380 

![20180917-1609-jpvpr](https://user-images.githubusercontent.com/5667740/45626169-75900180-ba97-11e8-932a-fccc3320d3f0.png)

**Closed by sshaman1101** 2018-09-17 13:33 UTC
Labels: S: Worker, T: bug
